---
title: "Incidence Rate Map"
author: "Sahinya Akila, Prachi Jaiswal"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(sf)
library(broom)
library(readxl)
library(rgdal)
library(tigris)
```

```{r}
full_data <- read_csv(file.choose())
 
```

```{r}
shapefile <- readOGR(dsn = paste0(getwd(), "/Data/SA3_2011/"))

shapefile_df <- fortify(shapefile, region = "SA3_NAME11")

data_avg_2007 <- full_data %>% 
  group_by(SA3_NAME_2011, Year) %>% 
  summarise(mean_incidence_rate = mean(BFV_IRLA)) %>% 
  filter(Year == "2007")

shapefile_df <- shapefile_df %>%
  left_join(. , data_avg_2007, by=c("id"="SA3_NAME_2011"))

ggplot() +
geom_path(data = shapefile_df, 
          aes(x = long, y = lat, group = group),
          color = 'black', fill = 'white', size = .2)

library(viridis)
ggplot() +
  geom_polygon(data = shapefile_df, 
               aes(fill = mean_incidence_rate, x = long, y = lat, group = group)) +
  theme_void() +
  scale_fill_viridis(trans = "log", breaks=c(1,5,10,20,50,100)) +
  coord_map()


```

```{r, connection_map}

filename <- file.choose()
virus_list <-  c("Dengue", 
                   "West_Nile_Kunjin", 
                   "Zika", 
                   "Chikungunya",
                   "Japanese_Encephalitis_Virus")
  
con_data <- data.frame()
  
for(i in 1:5)
{
  con_data <- rbind(con_data, read_excel(filename, sheet = i) %>%
                      add_column(Virus = virus_list[i]))
}


```
